/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Memo API
 * Notionライクメモアプリ API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from './axios-instance';
import type { ErrorType } from './axios-instance';
export interface PageResponseDto {
  id: string;
  title: string;
  icon?: string;
  parentId?: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreatePageDto {
  /** ページタイトル */
  title: string;
  /** ページアイコン */
  icon?: string;
  /** 親ページID */
  parentId?: string;
}

export interface UpdatePageDto {
  /** ページタイトル */
  title?: string;
  /** ページアイコン */
  icon?: string;
  /** 親ページID */
  parentId?: string;
}

export type BlockResponseDtoContent = { [key: string]: unknown };

export type BlockResponseDtoProps = { [key: string]: unknown };

export interface BlockResponseDto {
  id: string;
  type: string;
  content: BlockResponseDtoContent;
  props?: BlockResponseDtoProps;
  order: number;
  pageId: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * BlockNoteコンテンツ（JSON）
 */
export type CreateBlockDtoContent = { [key: string]: unknown };

/**
 * BlockNoteプロパティ（JSON）
 */
export type CreateBlockDtoProps = { [key: string]: unknown };

export interface CreateBlockDto {
  /** ブロックタイプ */
  type: string;
  /** BlockNoteコンテンツ（JSON） */
  content: CreateBlockDtoContent;
  /** BlockNoteプロパティ（JSON） */
  props?: CreateBlockDtoProps;
  /** 表示順序 */
  order: number;
  /** 所属ページID */
  pageId: string;
}

/**
 * BlockNoteコンテンツ（JSON）
 */
export type UpdateBlockDtoContent = { [key: string]: unknown };

/**
 * BlockNoteプロパティ（JSON）
 */
export type UpdateBlockDtoProps = { [key: string]: unknown };

export interface UpdateBlockDto {
  /** ブロックタイプ */
  type?: string;
  /** BlockNoteコンテンツ（JSON） */
  content?: UpdateBlockDtoContent;
  /** BlockNoteプロパティ（JSON） */
  props?: UpdateBlockDtoProps;
  /** 表示順序 */
  order?: number;
}

/**
 * @summary 全ページ取得
 */
export const pagesControllerFindAll = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<PageResponseDto[]>(
      {url: `/pages`, method: 'GET', signal
    },
      );
    }
  



export const getPagesControllerFindAllQueryKey = () => {
    return [
    `/pages`
    ] as const;
    }

    
export const getPagesControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof pagesControllerFindAll>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindAll>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPagesControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof pagesControllerFindAll>>> = ({ signal }) => pagesControllerFindAll(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PagesControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof pagesControllerFindAll>>>
export type PagesControllerFindAllQueryError = ErrorType<unknown>


export function usePagesControllerFindAll<TData = Awaited<ReturnType<typeof pagesControllerFindAll>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof pagesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof pagesControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePagesControllerFindAll<TData = Awaited<ReturnType<typeof pagesControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof pagesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof pagesControllerFindAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePagesControllerFindAll<TData = Awaited<ReturnType<typeof pagesControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 全ページ取得
 */

export function usePagesControllerFindAll<TData = Awaited<ReturnType<typeof pagesControllerFindAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindAll>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPagesControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary ページ作成
 */
export const pagesControllerCreate = (
    createPageDto: CreatePageDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PageResponseDto>(
      {url: `/pages`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createPageDto, signal
    },
      );
    }
  


export const getPagesControllerCreateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pagesControllerCreate>>, TError,{data: CreatePageDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof pagesControllerCreate>>, TError,{data: CreatePageDto}, TContext> => {

const mutationKey = ['pagesControllerCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pagesControllerCreate>>, {data: CreatePageDto}> = (props) => {
          const {data} = props ?? {};

          return  pagesControllerCreate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PagesControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof pagesControllerCreate>>>
    export type PagesControllerCreateMutationBody = CreatePageDto
    export type PagesControllerCreateMutationError = ErrorType<unknown>

    /**
 * @summary ページ作成
 */
export const usePagesControllerCreate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pagesControllerCreate>>, TError,{data: CreatePageDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pagesControllerCreate>>,
        TError,
        {data: CreatePageDto},
        TContext
      > => {

      const mutationOptions = getPagesControllerCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary ルートページ取得
 */
export const pagesControllerFindRootPages = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<PageResponseDto[]>(
      {url: `/pages/root`, method: 'GET', signal
    },
      );
    }
  



export const getPagesControllerFindRootPagesQueryKey = () => {
    return [
    `/pages/root`
    ] as const;
    }

    
export const getPagesControllerFindRootPagesQueryOptions = <TData = Awaited<ReturnType<typeof pagesControllerFindRootPages>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindRootPages>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPagesControllerFindRootPagesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof pagesControllerFindRootPages>>> = ({ signal }) => pagesControllerFindRootPages(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindRootPages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PagesControllerFindRootPagesQueryResult = NonNullable<Awaited<ReturnType<typeof pagesControllerFindRootPages>>>
export type PagesControllerFindRootPagesQueryError = ErrorType<unknown>


export function usePagesControllerFindRootPages<TData = Awaited<ReturnType<typeof pagesControllerFindRootPages>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindRootPages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof pagesControllerFindRootPages>>,
          TError,
          Awaited<ReturnType<typeof pagesControllerFindRootPages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePagesControllerFindRootPages<TData = Awaited<ReturnType<typeof pagesControllerFindRootPages>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindRootPages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof pagesControllerFindRootPages>>,
          TError,
          Awaited<ReturnType<typeof pagesControllerFindRootPages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePagesControllerFindRootPages<TData = Awaited<ReturnType<typeof pagesControllerFindRootPages>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindRootPages>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ルートページ取得
 */

export function usePagesControllerFindRootPages<TData = Awaited<ReturnType<typeof pagesControllerFindRootPages>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindRootPages>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPagesControllerFindRootPagesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary ページ取得
 */
export const pagesControllerFindById = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PageResponseDto>(
      {url: `/pages/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getPagesControllerFindByIdQueryKey = (id?: string,) => {
    return [
    `/pages/${id}`
    ] as const;
    }

    
export const getPagesControllerFindByIdQueryOptions = <TData = Awaited<ReturnType<typeof pagesControllerFindById>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPagesControllerFindByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof pagesControllerFindById>>> = ({ signal }) => pagesControllerFindById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PagesControllerFindByIdQueryResult = NonNullable<Awaited<ReturnType<typeof pagesControllerFindById>>>
export type PagesControllerFindByIdQueryError = ErrorType<void>


export function usePagesControllerFindById<TData = Awaited<ReturnType<typeof pagesControllerFindById>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof pagesControllerFindById>>,
          TError,
          Awaited<ReturnType<typeof pagesControllerFindById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePagesControllerFindById<TData = Awaited<ReturnType<typeof pagesControllerFindById>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof pagesControllerFindById>>,
          TError,
          Awaited<ReturnType<typeof pagesControllerFindById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePagesControllerFindById<TData = Awaited<ReturnType<typeof pagesControllerFindById>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ページ取得
 */

export function usePagesControllerFindById<TData = Awaited<ReturnType<typeof pagesControllerFindById>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPagesControllerFindByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary ページ更新
 */
export const pagesControllerUpdate = (
    id: string,
    updatePageDto: UpdatePageDto,
 ) => {
      
      
      return customInstance<PageResponseDto>(
      {url: `/pages/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updatePageDto
    },
      );
    }
  


export const getPagesControllerUpdateMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pagesControllerUpdate>>, TError,{id: string;data: UpdatePageDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof pagesControllerUpdate>>, TError,{id: string;data: UpdatePageDto}, TContext> => {

const mutationKey = ['pagesControllerUpdate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pagesControllerUpdate>>, {id: string;data: UpdatePageDto}> = (props) => {
          const {id,data} = props ?? {};

          return  pagesControllerUpdate(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PagesControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof pagesControllerUpdate>>>
    export type PagesControllerUpdateMutationBody = UpdatePageDto
    export type PagesControllerUpdateMutationError = ErrorType<void>

    /**
 * @summary ページ更新
 */
export const usePagesControllerUpdate = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pagesControllerUpdate>>, TError,{id: string;data: UpdatePageDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pagesControllerUpdate>>,
        TError,
        {id: string;data: UpdatePageDto},
        TContext
      > => {

      const mutationOptions = getPagesControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary ページ削除
 */
export const pagesControllerDelete = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/pages/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getPagesControllerDeleteMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pagesControllerDelete>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof pagesControllerDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['pagesControllerDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pagesControllerDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  pagesControllerDelete(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PagesControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof pagesControllerDelete>>>
    
    export type PagesControllerDeleteMutationError = ErrorType<void>

    /**
 * @summary ページ削除
 */
export const usePagesControllerDelete = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pagesControllerDelete>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pagesControllerDelete>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPagesControllerDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary 子ページ取得
 */
export const pagesControllerFindChildren = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PageResponseDto[]>(
      {url: `/pages/${id}/children`, method: 'GET', signal
    },
      );
    }
  



export const getPagesControllerFindChildrenQueryKey = (id?: string,) => {
    return [
    `/pages/${id}/children`
    ] as const;
    }

    
export const getPagesControllerFindChildrenQueryOptions = <TData = Awaited<ReturnType<typeof pagesControllerFindChildren>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindChildren>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPagesControllerFindChildrenQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof pagesControllerFindChildren>>> = ({ signal }) => pagesControllerFindChildren(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindChildren>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PagesControllerFindChildrenQueryResult = NonNullable<Awaited<ReturnType<typeof pagesControllerFindChildren>>>
export type PagesControllerFindChildrenQueryError = ErrorType<unknown>


export function usePagesControllerFindChildren<TData = Awaited<ReturnType<typeof pagesControllerFindChildren>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindChildren>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof pagesControllerFindChildren>>,
          TError,
          Awaited<ReturnType<typeof pagesControllerFindChildren>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePagesControllerFindChildren<TData = Awaited<ReturnType<typeof pagesControllerFindChildren>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindChildren>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof pagesControllerFindChildren>>,
          TError,
          Awaited<ReturnType<typeof pagesControllerFindChildren>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePagesControllerFindChildren<TData = Awaited<ReturnType<typeof pagesControllerFindChildren>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindChildren>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 子ページ取得
 */

export function usePagesControllerFindChildren<TData = Awaited<ReturnType<typeof pagesControllerFindChildren>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pagesControllerFindChildren>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPagesControllerFindChildrenQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary ページのブロック一覧取得
 */
export const blocksControllerFindByPageId = (
    pageId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<BlockResponseDto[]>(
      {url: `/blocks/page/${pageId}`, method: 'GET', signal
    },
      );
    }
  



export const getBlocksControllerFindByPageIdQueryKey = (pageId?: string,) => {
    return [
    `/blocks/page/${pageId}`
    ] as const;
    }

    
export const getBlocksControllerFindByPageIdQueryOptions = <TData = Awaited<ReturnType<typeof blocksControllerFindByPageId>>, TError = ErrorType<unknown>>(pageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blocksControllerFindByPageId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBlocksControllerFindByPageIdQueryKey(pageId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof blocksControllerFindByPageId>>> = ({ signal }) => blocksControllerFindByPageId(pageId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(pageId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof blocksControllerFindByPageId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BlocksControllerFindByPageIdQueryResult = NonNullable<Awaited<ReturnType<typeof blocksControllerFindByPageId>>>
export type BlocksControllerFindByPageIdQueryError = ErrorType<unknown>


export function useBlocksControllerFindByPageId<TData = Awaited<ReturnType<typeof blocksControllerFindByPageId>>, TError = ErrorType<unknown>>(
 pageId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof blocksControllerFindByPageId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof blocksControllerFindByPageId>>,
          TError,
          Awaited<ReturnType<typeof blocksControllerFindByPageId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBlocksControllerFindByPageId<TData = Awaited<ReturnType<typeof blocksControllerFindByPageId>>, TError = ErrorType<unknown>>(
 pageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blocksControllerFindByPageId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof blocksControllerFindByPageId>>,
          TError,
          Awaited<ReturnType<typeof blocksControllerFindByPageId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBlocksControllerFindByPageId<TData = Awaited<ReturnType<typeof blocksControllerFindByPageId>>, TError = ErrorType<unknown>>(
 pageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blocksControllerFindByPageId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ページのブロック一覧取得
 */

export function useBlocksControllerFindByPageId<TData = Awaited<ReturnType<typeof blocksControllerFindByPageId>>, TError = ErrorType<unknown>>(
 pageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blocksControllerFindByPageId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBlocksControllerFindByPageIdQueryOptions(pageId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary ブロック取得
 */
export const blocksControllerFindById = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<BlockResponseDto>(
      {url: `/blocks/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getBlocksControllerFindByIdQueryKey = (id?: string,) => {
    return [
    `/blocks/${id}`
    ] as const;
    }

    
export const getBlocksControllerFindByIdQueryOptions = <TData = Awaited<ReturnType<typeof blocksControllerFindById>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blocksControllerFindById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBlocksControllerFindByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof blocksControllerFindById>>> = ({ signal }) => blocksControllerFindById(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof blocksControllerFindById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BlocksControllerFindByIdQueryResult = NonNullable<Awaited<ReturnType<typeof blocksControllerFindById>>>
export type BlocksControllerFindByIdQueryError = ErrorType<void>


export function useBlocksControllerFindById<TData = Awaited<ReturnType<typeof blocksControllerFindById>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof blocksControllerFindById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof blocksControllerFindById>>,
          TError,
          Awaited<ReturnType<typeof blocksControllerFindById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBlocksControllerFindById<TData = Awaited<ReturnType<typeof blocksControllerFindById>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blocksControllerFindById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof blocksControllerFindById>>,
          TError,
          Awaited<ReturnType<typeof blocksControllerFindById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBlocksControllerFindById<TData = Awaited<ReturnType<typeof blocksControllerFindById>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blocksControllerFindById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary ブロック取得
 */

export function useBlocksControllerFindById<TData = Awaited<ReturnType<typeof blocksControllerFindById>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blocksControllerFindById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBlocksControllerFindByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary ブロック更新
 */
export const blocksControllerUpdate = (
    id: string,
    updateBlockDto: UpdateBlockDto,
 ) => {
      
      
      return customInstance<BlockResponseDto>(
      {url: `/blocks/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateBlockDto
    },
      );
    }
  


export const getBlocksControllerUpdateMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blocksControllerUpdate>>, TError,{id: string;data: UpdateBlockDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blocksControllerUpdate>>, TError,{id: string;data: UpdateBlockDto}, TContext> => {

const mutationKey = ['blocksControllerUpdate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blocksControllerUpdate>>, {id: string;data: UpdateBlockDto}> = (props) => {
          const {id,data} = props ?? {};

          return  blocksControllerUpdate(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BlocksControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof blocksControllerUpdate>>>
    export type BlocksControllerUpdateMutationBody = UpdateBlockDto
    export type BlocksControllerUpdateMutationError = ErrorType<void>

    /**
 * @summary ブロック更新
 */
export const useBlocksControllerUpdate = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blocksControllerUpdate>>, TError,{id: string;data: UpdateBlockDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blocksControllerUpdate>>,
        TError,
        {id: string;data: UpdateBlockDto},
        TContext
      > => {

      const mutationOptions = getBlocksControllerUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary ブロック削除
 */
export const blocksControllerDelete = (
    id: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/blocks/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getBlocksControllerDeleteMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blocksControllerDelete>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blocksControllerDelete>>, TError,{id: string}, TContext> => {

const mutationKey = ['blocksControllerDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blocksControllerDelete>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  blocksControllerDelete(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BlocksControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof blocksControllerDelete>>>
    
    export type BlocksControllerDeleteMutationError = ErrorType<void>

    /**
 * @summary ブロック削除
 */
export const useBlocksControllerDelete = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blocksControllerDelete>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blocksControllerDelete>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getBlocksControllerDeleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary ブロック作成
 */
export const blocksControllerCreate = (
    createBlockDto: CreateBlockDto,
 signal?: AbortSignal
) => {
      
      
      return customInstance<BlockResponseDto>(
      {url: `/blocks`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createBlockDto, signal
    },
      );
    }
  


export const getBlocksControllerCreateMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blocksControllerCreate>>, TError,{data: CreateBlockDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof blocksControllerCreate>>, TError,{data: CreateBlockDto}, TContext> => {

const mutationKey = ['blocksControllerCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blocksControllerCreate>>, {data: CreateBlockDto}> = (props) => {
          const {data} = props ?? {};

          return  blocksControllerCreate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BlocksControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof blocksControllerCreate>>>
    export type BlocksControllerCreateMutationBody = CreateBlockDto
    export type BlocksControllerCreateMutationError = ErrorType<unknown>

    /**
 * @summary ブロック作成
 */
export const useBlocksControllerCreate = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blocksControllerCreate>>, TError,{data: CreateBlockDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blocksControllerCreate>>,
        TError,
        {data: CreateBlockDto},
        TContext
      > => {

      const mutationOptions = getBlocksControllerCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
